### ISSUE TITLE
Problem with strandedness

### ISSUE THREAD

**Issue by amitjavilaventura** [PhanstielLab/bedtoolsr#10]
Hello,

I am using bedtoolsr::bt.intersect() and I want to specify strandedness. Nevertheless, when I specify `s=T` and `s=F`, the number of output regions is always the same.

For example:

```
> bedtoolsr::bt.intersect(a = a, b = b, s = T, u = T) %>% nrow()
[1] 8092
> bedtoolsr::bt.intersect(a = a, b = b, S = T, u = T) %>% nrow()
[1] 1337
> bedtoolsr::bt.intersect(a = a, b = b, s = F, u = T) %>% nrow()
[1] 8092
```

Doing the same command with the command-line bedtools:

```
$ bedtools intersect -s -u -a a.tmp.bed -b b.tmp.bed | wc -l
8092
$ bedtools intersect -S -u -a a.tmp.bed -b b.tmp.bed | wc -l
1337
$ bedtools intersect -u -a a.tmp.bed -b b.tmp.bed | wc -l
8594
```

It looks like with `bedtoolsr::bt.intersect()` the strandedness is always the same unless if I specify that I want a different strandedness, when in theory, if I specify s = F, I should get intersections regardless the strand. 

My `bedtools` version is `2.29.2`, and my `bedtoolsr` version is `2.30.0.1`. When I load `bedtoolsr` a warning says that it was developed under `bedtools` version `2.30`. Can this be the source of my problem??

Thank you very much.

Adrià

**Comment by cwenger** [comment]
Hi Adrià,

There was some counterintuitive logic where passing anything other than `NULL` to an argument (even `FALSE`) led it to being included in the bedtools call, which is why you were getting the same results with your first and third bedtoolsr commands. This has been changed. Thanks for the bug report!
