### ISSUE TITLE
bedtoolsr installation fails due to "sh: 1: bedtools: not found" error

### ISSUE THREAD

**Issue by jordimaggi** [PhanstielLab/bedtoolsr#11]
Hi,

I am trying to run `CNV-ClinViewer` locally through RStudio Server, installed on Ubuntu 20.04 LTS. During the installation of all dependencies, the installation of `bedtoolsr` fails because RStudio Server cannot find `bedtools`. However, `bedtools `v2.30.0 is installed on the system and on PATH.

I also tried to manually set the path to bedtools manually like so: `options(bedtools.path = "/home/analyst/anaconda3/bin/")`.

I tried the same thing on Windows WSL, and faced the exact same problem.

That did not help either. Do you have any idea on how to overcome this problem?

**Comment by cwenger** [comment]
Hi Jordi,

I don't know much about RStudio Server but I did confirm just now that everything works correctly for me on both Ubuntu 20.04 and WSL (Ubuntu version 1). I would guess this is due to R having a different PATH than the rest of your system. Can you try putting `bedtools` somewhere that it should definitely be picked up, like `/usr/bin`?

**Comment by jordimaggi** [comment]
Hi Craig,

thanks for the reply. 
Yes, as I matter of fact I found out that the PATH variable within RStudio was different from the rest of my system. I then added the `/home/analyst/anaconda3/bin/` to the PATH variable in RStudio and that solved it, at least for the current session.

**Comment by cwenger** [comment]
Great, I will close the issue for now.

**Comment by Susung-CMU** [comment]
> Hi Craig,
> 
> thanks for the reply. Yes, as I matter of fact I found out that the PATH variable within RStudio was different from the rest of my system. I then added the `/home/analyst/anaconda3/bin/` to the PATH variable in RStudio and that solved it, at least for the current session.

Hi Jordi

I met the same problem. And how can you "added the `/home/analyst/anaconda3/bin/` to the PATH variable in RStudio"?

**Comment by cwenger** [comment]
Is this on Mac? If so, it seems like applications launched from the terminal have a different `PATH` than those launched from Finder, like RStudio. I am not sure how to permanently modify the latter but from within RStudio you should be able to run this to temporarily modify it:

`Sys.setenv(PATH = paste(Sys.getenv("PATH"), "/home/analyst/anaconda3/bin", sep = ":"))`
