### ISSUE TITLE
Keep randomly getting an error when using bt.sort or bt.merge. The error always takes the form of "It looks as though you have less than...columns at line...in file...Are you sure your files are tab-delimited?"

### ISSUE THREAD

**Issue by blc49** [PhanstielLab/bedtoolsr#13]
I can manually inspect the bed files and there is always 3 columns of data at the line the error specifies.

Usually if I re-install the package the error will go away for a little while, but it continues to come back. 

Package: bedtoolsr
Encoding: UTF-8
Type: Package
Title: Bedtools Wrapper
Version: 2.30.0-5
Date: 2022-11-08
Author: Mayura Patwardhan, Craig Wenger, Eric Davis, Doug Phanstiel
Maintainer: Doug Phanstiel <douglas_phanstiel@med.unc.edu>
Description: Wrapper library for the bedtools utilities for genome arithmetic.
Imports: utils
Suggests: testthat
License: MIT + file LICENSE
RoxygenNote: 7.2.1
RemoteType: github
RemoteHost: api.github.com
RemoteRepo: bedtoolsr
RemoteUsername: PhanstielLab
RemoteRef: HEAD
RemoteSha: cce152f1ce653771d8d41431e0d12e4ef9c42193
GithubRepo: bedtoolsr
GithubUsername: PhanstielLab
GithubRef: HEAD
GithubSHA1: cce152f1ce653771d8d41431e0d12e4ef9c42193
NeedsCompilation: no
Packaged: 2023-01-25 19:08:52 UTC; ben
Built: R 4.1.1; ; 2023-01-25 19:08:53 UTC; unix

-- File: /Library/Frameworks/R.framework/Versions/4.1/Resources/library/bedtoolsr/Meta/package.rds

**Comment by cwenger** [comment]
Can you provide example code and input files to reproduce the error? What OS are you using? Also can you confirm you are using bedtools v2.30.0 by running `bedtools --version` from the terminal?

**Comment by blc49** [comment]
Update: I've included some of the information you asked for below. But in the meantime I have gotten it to work. I receive the same error when trying to sort or merge a GRanges object. But if I convert that to a data.frame with only "chrom", "chromStart", and "chromEnd" columns then it works.

Example code that gives error:
GRanges.obj <- bt.sort(GRanges.obj)

or

GRanges.obj <- bt.merge(GRanges.obj)

Example code that works:
df <- as.data.frame(GRanges.obj)
df <- df[,1:3]
df <- bt.sort(df)
df <- bt.merge(df)


Package: bedtoolsr
Encoding: UTF-8
Type: Package
Title: Bedtools Wrapper
Version: 2.30.0-5
Date: 2022-11-08
Author: Mayura Patwardhan, Craig Wenger, Eric Davis, Doug Phanstiel
Maintainer: Doug Phanstiel <douglas_phanstiel@med.unc.edu>
Description: Wrapper library for the bedtools utilities for genome arithmetic.
Imports: utils
Suggests: testthat
License: MIT + file LICENSE
RoxygenNote: 7.2.1
RemoteType: github
RemoteHost: api.github.com
RemoteRepo: bedtoolsr
RemoteUsername: PhanstielLab
RemoteRef: HEAD
RemoteSha: cce152f1ce653771d8d41431e0d12e4ef9c42193
GithubRepo: bedtoolsr
GithubUsername: PhanstielLab
GithubRef: HEAD
GithubSHA1: cce152f1ce653771d8d41431e0d12e4ef9c42193
NeedsCompilation: no
Packaged: 2023-01-25 19:08:52 UTC; ben
Built: R 4.1.1; ; 2023-01-25 19:08:53 UTC; unix

-- File: /Library/Frameworks/R.framework/Versions/4.1/Resources/library/bedtoolsr/Meta/package.rds 

R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS 13.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ggplot2_3.4.0                             DiffBind_3.4.11                          
 [3] SummarizedExperiment_1.24.0               MatrixGenerics_1.6.0                     
 [5] matrixStats_0.63.0                        dplyr_1.0.10                             
 [7] openxlsx_4.2.5.1                          org.Mm.eg.db_3.14.0                      
 [9] rtracklayer_1.54.0                        TxDb.Mmusculus.UCSC.mm10.knownGene_3.10.0
[11] GenomicFeatures_1.46.5                    AnnotationDbi_1.56.2                     
[13] Biobase_2.54.0                            ChIPseeker_1.30.3                        
[15] ChIPpeakAnno_3.28.1                       GenomicRanges_1.46.1                     
[17] GenomeInfoDb_1.30.1                       IRanges_2.28.0                           
[19] S4Vectors_0.32.4                          BiocGenerics_0.40.0                      
[21] bedtoolsr_2.30.0-5

% bedtools --version
bedtools v2.30.0

**Comment by cwenger** [comment]
That makes sense. GRanges might have more/different information than BED files and confuse the parsing. Definitely best to convert to a data frame with the minimum required information first, as you discovered.
