### ISSUE TITLE
bedtoolsr::bt.multicov issue

### ISSUE THREAD

**Issue by Adnanhashim** [PhanstielLab/bedtoolsr#14]
Hi,

First and foremost, thank you for the R version of bedtools. I'm attempting to use bedtools multicov but receiving the following error.

> bedfile <- read.table("peaks_mod.bed", header = F, sep = "\t")
> head(bedfile)
     V1        V2        V3 V4
1  chr8  85554228  85555389  -
2 chr11  60877576  60879894  -
3 chr12 108793341 108795193  -
4  chr2  92432803  92434088  -
5 chr13 100124401 100125923  -
6  chr7 109519172 109521109  -

> bamfile <-BamFile("bam_100k_mm10_chip_sorted.bam") #to check if bamfile is loaded corrected i did.
> indexBam(bamfile)
      E14_K4_100k_mm10_chip_sorted.bam 
"E14_K4_100k_mm10_chip_sorted.bam.bai" 

> cov = bedtoolsr::bt.multicov(bams = bamfile, bed = bedfile)
**Error in as.data.frame.default(x[[i]], optional = TRUE) : 
  cannot coerce class ‘structure("BamFile", package = "Rsamtools")’ to a data.frame**

could you please tell me how to solve it ? Thanks 

i have done same thing with bedtools without any issue. 

bedtools multicov -bams bam_100k_mm10_chip_sorted.bam -bed peaks_mod.bed > coverage.bed

head coverage.bed
chr8	85554228	85555389	-	1691
chr11	60877576	60879894	-	2410
chr12	108793341	108795193	-	3334
chr2	92432803	92434088	-	1043
chr13	100124401	100125923	-	1479
chr7	109519172	109521109	-	2703
chr16	35489817	35491172	-	2748
chr10	117844804	117846650	-	2151
chr6	119175202	119176003	-	1173
chr6	113075180	113077265	-	1608

**Comment by cwenger** [comment]
Hi Adnan,

Bedtools isn't set up to natively handle the BamFile structure. The easiest thing to do would be to specify the filename instead for the bam file, or both the bam file and the bed file. For example:

```
cov = bedtoolsr::bt.multicov(bams = "bam_100k_mm10_chip_sorted.bam", bed = bedfile)
cov = bedtoolsr::bt.multicov(bams = "bam_100k_mm10_chip_sorted.bam", bed = "peaks_mod.bed")
```

should both work.

I will close the issue for now but feel free to re-open if this doesn't work.
