### ISSUE TITLE
Bug report (Failure due to the special characters)

### ISSUE THREAD

**Issue by rongxinzh** [PhanstielLab/bedtoolsr#7]
Dear developers, **_bedtoolsr_** is an extremely useful software for me, but a potential issue occurred when I use the **_bedtoolsr_** package. 
Here is an example of the issue.
`
> A.bed <- data.frame(chrom=c("chr1", "chr1"), start=c(10, 30), end=c(20, 40),source=c("pubmed","pubmed"))
> B.bed <- data.frame(chrom=c("chr1"), start=15, end=20)
> #The result is fine
> bedtoolsr::bt.intersect(A.bed, B.bed)
    V1 V2 V3     V4
1 chr1 15 20 pubmed
`

However, when added another column which contains the special character " **'** ", and problem happens.

`
> A.bed <- data.frame(chrom=c("chr1", "chr1"), start=c(10, 30), end=c(20, 40), anno = c("5'UTR", "CDS"), source=c("pubmed","pubmed"))
> B.bed <- data.frame(chrom=c("chr1"), start=15, end=20)
> #problem occured
> bedtoolsr::bt.intersect(A.bed, B.bed)
[1] V1 V2 V3 V4 V5
<0 rows> (or 0-length row.names)
Warning message:
In utils::read.table(tempfile, header = FALSE, sep = "\t") :
  incomplete final line found by readTableHeader on '/tmp/RtmpHeeAXx/bedtoolsr15c554c9da9df.txt'
`

This problem may occur if the contents of the variables contain special characters and **_bedtoolsr_** may not handle them specially. 

Best regards,

**Comment by rongxinzh** [comment]
My _**bedtoolsr**_ was built with bedtools version 2.29.0.

**Comment by cwenger** [comment]
Sorry for the long delay in getting back to you, I had accidentally unwatched the repository.

I fixed this by removing the single quote as a quoting character when reading the file. I think this should be OK for these types of files. Thanks for the bug report!
