### ISSUE TITLE
bt.complement error

### ISSUE THREAD

**Issue by RegnerM2015** [PhanstielLab/bedtoolsr#8]
Hi @cwenger @dphansti ,

I am having trouble implementing bt.complement. Ultimately, I want to create a bed file that is the complement of a coding gene annotation (gtf/bed) file. So a bed file of all non-coding genomic regions (hg38).  

If there is a publicly available non-coding annotation file for hg38, please let me know!

My subsetted data is attached for a reproducible example:

[genes.sub.txt](https://github.com/PhanstielLab/bedtoolsr/files/6053389/genes.sub.txt)
[genome.sub.txt](https://github.com/PhanstielLab/bedtoolsr/files/6053390/genome.sub.txt)

```
> head(genes.sub)
  V1    V2    V3
1 1  11869 14409
2 1  14404 29570
3 1  17369 17436
4 1  29554 31109
5 1  34554 36081
6 1  52473 53312
> head(genome.sub)
  V1        V2
1  1 248956422
2  2 242193529
3  3 198295559
4  4 190214555
5  5 181538259
6  6 170805979
> bt.complement(i=genes.sub,g=genome.sub)
Error: requested chromosome 1  does not exist in the genome file /tmp/RtmpjEuJzC/g_1.txt. Exiting.
data frame with 0 columns and 0 rows
```

**Comment by dphansti** [comment]
You might have to add ‘chr’ to all of your chomosomes.  E.g. chr1

**Comment by cwenger** [comment]
Hi @RegnerM2015,

I can't seem to reproduce your error:

```
> head(genes.sub)
  V1    V2    V3
1  1 11869 14409
2  1 14404 29570
3  1 17369 17436
4  1 29554 31109
5  1 34554 36081
6  1 52473 53312
> head(genome.sub)
  V1        V2
1  1 248956422
2  2 242193529
3  3 198295559
4  4 190214555
5  5 181538259
6  6 170805979
> bt.complement(i=genes.sub,g=genome.sub)
   V1     V2        V3
1   1      0     11869
2   1  31109     34554
3   1  36081     52473
4   1  53312     62948
5   1  63887     69091
6   1  70008     89295
7   1 133723 248956422
8   2      0 242193529
9   3      0 198295559
10  4      0 190214555
11  5      0 181538259
12  6      0 170805979
13  7      0 159345973
14  8      0 145138636
15  9      0 138394717
16 10      0 133797422
```

Does it work for you when you use bedtools from the command line (note you may need to changes the spaces to tabs in your input files)? What version of bedtools are you using?

**Comment by RegnerM2015** [comment]
Hi @cwenger,

I have 2.29.2 version of bedrolls installed. I will try 2.29.0 next.

Thanks!

**Comment by cwenger** [comment]
I did a [release](https://github.com/PhanstielLab/bedtoolsr/releases/tag/v2.30.0-1) this morning for bedtools 2.30.0 (which was released about a month ago); you could try that instead/also.

**Comment by RegnerM2015** [comment]
My bad, I meant to say 2.30.0. I will keep you updated!

**Comment by RegnerM2015** [comment]
Thanks for your help! Version 2.30.0 is the solution to my problem!
