### ISSUE TITLE
Default sorting of genome file does not work for Fisher function

### ISSUE THREAD

**Issue by agduncan94** [PhanstielLab/bedtoolsr#9]
Thanks for making this wrapper! I ran into this issue with version 2.30.0.1.

I was attempting to run bedtools fisher on two bed files and I got the following error:
```
Error: Sorted input specified, but the file <tmp file> has the following record with a different sort order than the genomeFile /Users/andrewduncan/Library/R/4.0/library/bedtoolsr/data/mm10
```

I had sorted the two bed files based on the information found on the Bedtools Fisher page (https://bedtools.readthedocs.io/en/latest/content/tools/fisher.html), but it seems like the genome file also needs to be sorted as well. I ran the same sort command on the mm10 file from the above error and the Fisher command now works.

I'm not sure if there are any implications for other functions if you sort the genome file in this way (sort -k1,1 -k2,2n), but it may be useful to have the genome files sorted this way by default.

**Comment by cwenger** [comment]
Thanks for the suggestion!
